server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/creditcard?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      com.bank.credit_card_service: ERROR
